### ISSUE TITLE
Backtrace form user

### ISSUE THREAD

**Issue by schriftgestalt** [markmonroy/FillBackgroundPath#4]
```
Details:
Traceback (most recent call last):

 File "GlyphsApp/GlyphsApp/plugins.py", line 1412, in raiseException_

 File "GlyphsApp/GlyphsApp/plugins.py", line 1228, in drawBackgroundForLayer_options_

 File "plugin.py", line 33, in background
   if layer.background.bezierPath:
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^

AttributeError: 'NoneType' object has no attribute 'bezierPath'

App:3.3-3315 Plugin:1.1-4 System:14.5.0 
```

**Comment by schriftgestalt** [comment]
this is fixed by the pull request I send some time ago.

**Comment by markyehan** [comment]
Hi Georg, I encountered this error as well. I've removed the existing plugin, both on Plugin Manager and in the Plugin folder as well but keep getting this error over and over again.

**Comment by schriftgestalt** [comment]
I fixed that and send a pull request. But is wasn’t merged, yet.
